<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>VPKMerge</RootNamespace>
    <AssemblyName>VPKMerge</AssemblyName>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- https://www.nuget.org/packages/ValvePak -->
    <PackageReference Include="ValvePak" Version="4.0.0.142" />
  </ItemGroup>

</Project>
